"""
Display-name -> Balatro 1.0.1o internal key tables for the oracle.

GENERATED by mp/oracle/blueprint_runner (one-off extraction of key/name pairs from the
game's center tables).  Names are what the seed analyzers (Immolate / TheSoul / Blueprint)
print; keys are G.P_CENTERS / G.P_BLINDS / G.P_TAGS keys.  A few analyzer names differ from
the game's display name; ANALYZER_ALIASES covers those.
"""

from __future__ import annotations

# 150 jokers, in game `order` (== G.P_CENTER_POOLS.Joker order; rarity pools are this order filtered by rarity)
JOKERS = {
    "Joker": "j_joker",
    "Greedy Joker": "j_greedy_joker",
    "Lusty Joker": "j_lusty_joker",
    "Wrathful Joker": "j_wrathful_joker",
    "Gluttonous Joker": "j_gluttenous_joker",
    "Jolly Joker": "j_jolly",
    "Zany Joker": "j_zany",
    "Mad Joker": "j_mad",
    "Crazy Joker": "j_crazy",
    "Droll Joker": "j_droll",
    "Sly Joker": "j_sly",
    "Wily Joker": "j_wily",
    "Clever Joker": "j_clever",
    "Devious Joker": "j_devious",
    "Crafty Joker": "j_crafty",
    "Half Joker": "j_half",
    "Joker Stencil": "j_stencil",
    "Four Fingers": "j_four_fingers",
    "Mime": "j_mime",
    "Credit Card": "j_credit_card",
    "Ceremonial Dagger": "j_ceremonial",
    "Banner": "j_banner",
    "Mystic Summit": "j_mystic_summit",
    "Marble Joker": "j_marble",
    "Loyalty Card": "j_loyalty_card",
    "8 Ball": "j_8_ball",
    "Misprint": "j_misprint",
    "Dusk": "j_dusk",
    "Raised Fist": "j_raised_fist",
    "Chaos the Clown": "j_chaos",
    "Fibonacci": "j_fibonacci",
    "Steel Joker": "j_steel_joker",
    "Scary Face": "j_scary_face",
    "Abstract Joker": "j_abstract",
    "Delayed Gratification": "j_delayed_grat",
    "Hack": "j_hack",
    "Pareidolia": "j_pareidolia",
    "Gros Michel": "j_gros_michel",
    "Even Steven": "j_even_steven",
    "Odd Todd": "j_odd_todd",
    "Scholar": "j_scholar",
    "Business Card": "j_business",
    "Supernova": "j_supernova",
    "Ride the Bus": "j_ride_the_bus",
    "Space Joker": "j_space",
    "Egg": "j_egg",
    "Burglar": "j_burglar",
    "Blackboard": "j_blackboard",
    "Runner": "j_runner",
    "Ice Cream": "j_ice_cream",
    "DNA": "j_dna",
    "Splash": "j_splash",
    "Blue Joker": "j_blue_joker",
    "Sixth Sense": "j_sixth_sense",
    "Constellation": "j_constellation",
    "Hiker": "j_hiker",
    "Faceless Joker": "j_faceless",
    "Green Joker": "j_green_joker",
    "Superposition": "j_superposition",
    "To Do List": "j_todo_list",
    "Cavendish": "j_cavendish",
    "Card Sharp": "j_card_sharp",
    "Red Card": "j_red_card",
    "Madness": "j_madness",
    "Square Joker": "j_square",
    "Seance": "j_seance",
    "Riff-raff": "j_riff_raff",
    "Vampire": "j_vampire",
    "Shortcut": "j_shortcut",
    "Hologram": "j_hologram",
    "Vagabond": "j_vagabond",
    "Baron": "j_baron",
    "Cloud 9": "j_cloud_9",
    "Rocket": "j_rocket",
    "Obelisk": "j_obelisk",
    "Midas Mask": "j_midas_mask",
    "Luchador": "j_luchador",
    "Photograph": "j_photograph",
    "Gift Card": "j_gift",
    "Turtle Bean": "j_turtle_bean",
    "Erosion": "j_erosion",
    "Reserved Parking": "j_reserved_parking",
    "Mail-In Rebate": "j_mail",
    "To the Moon": "j_to_the_moon",
    "Hallucination": "j_hallucination",
    "Fortune Teller": "j_fortune_teller",
    "Juggler": "j_juggler",
    "Drunkard": "j_drunkard",
    "Stone Joker": "j_stone",
    "Golden Joker": "j_golden",
    "Lucky Cat": "j_lucky_cat",
    "Baseball Card": "j_baseball",
    "Bull": "j_bull",
    "Diet Cola": "j_diet_cola",
    "Trading Card": "j_trading",
    "Flash Card": "j_flash",
    "Popcorn": "j_popcorn",
    "Spare Trousers": "j_trousers",
    "Ancient Joker": "j_ancient",
    "Ramen": "j_ramen",
    "Walkie Talkie": "j_walkie_talkie",
    "Seltzer": "j_selzer",
    "Castle": "j_castle",
    "Smiley Face": "j_smiley",
    "Campfire": "j_campfire",
    "Golden Ticket": "j_ticket",
    "Mr. Bones": "j_mr_bones",
    "Acrobat": "j_acrobat",
    "Sock and Buskin": "j_sock_and_buskin",
    "Swashbuckler": "j_swashbuckler",
    "Troubadour": "j_troubadour",
    "Certificate": "j_certificate",
    "Smeared Joker": "j_smeared",
    "Throwback": "j_throwback",
    "Hanging Chad": "j_hanging_chad",
    "Rough Gem": "j_rough_gem",
    "Bloodstone": "j_bloodstone",
    "Arrowhead": "j_arrowhead",
    "Onyx Agate": "j_onyx_agate",
    "Glass Joker": "j_glass",
    "Showman": "j_ring_master",
    "Flower Pot": "j_flower_pot",
    "Blueprint": "j_blueprint",
    "Wee Joker": "j_wee",
    "Merry Andy": "j_merry_andy",
    "Oops! All 6s": "j_oops",
    "The Idol": "j_idol",
    "Seeing Double": "j_seeing_double",
    "Matador": "j_matador",
    "Hit the Road": "j_hit_the_road",
    "The Duo": "j_duo",
    "The Trio": "j_trio",
    "The Family": "j_family",
    "The Order": "j_order",
    "The Tribe": "j_tribe",
    "Stuntman": "j_stuntman",
    "Invisible Joker": "j_invisible",
    "Brainstorm": "j_brainstorm",
    "Satellite": "j_satellite",
    "Shoot the Moon": "j_shoot_the_moon",
    "Driver's License": "j_drivers_license",
    "Cartomancer": "j_cartomancer",
    "Astronomer": "j_astronomer",
    "Burnt Joker": "j_burnt",
    "Bootstraps": "j_bootstraps",
    "Caino": "j_caino",
    "Triboulet": "j_triboulet",
    "Yorick": "j_yorick",
    "Chicot": "j_chicot",
    "Perkeo": "j_perkeo",
}

# 22 tarots in game order
TAROTS = {
    "The Fool": "c_fool",
    "The Magician": "c_magician",
    "The High Priestess": "c_high_priestess",
    "The Empress": "c_empress",
    "The Emperor": "c_emperor",
    "The Hierophant": "c_heirophant",
    "The Lovers": "c_lovers",
    "The Chariot": "c_chariot",
    "Justice": "c_justice",
    "The Hermit": "c_hermit",
    "The Wheel of Fortune": "c_wheel_of_fortune",
    "Strength": "c_strength",
    "The Hanged Man": "c_hanged_man",
    "Death": "c_death",
    "Temperance": "c_temperance",
    "The Devil": "c_devil",
    "The Tower": "c_tower",
    "The Star": "c_star",
    "The Moon": "c_moon",
    "The Sun": "c_sun",
    "Judgement": "c_judgement",
    "The World": "c_world",
}

# 12 planets in game order (Planet X / Ceres / Eris are softlocked until their hand is played)
PLANETS = {
    "Mercury": "c_mercury",
    "Venus": "c_venus",
    "Earth": "c_earth",
    "Mars": "c_mars",
    "Jupiter": "c_jupiter",
    "Saturn": "c_saturn",
    "Uranus": "c_uranus",
    "Neptune": "c_neptune",
    "Pluto": "c_pluto",
    "Planet X": "c_planet_x",
    "Ceres": "c_ceres",
    "Eris": "c_eris",
}

# 18 spectrals in game order; c_soul and c_black_hole are UNAVAILABLE in the pool (forced via the soul_ roll)
SPECTRALS = {
    "Familiar": "c_familiar",
    "Grim": "c_grim",
    "Incantation": "c_incantation",
    "Talisman": "c_talisman",
    "Aura": "c_aura",
    "Wraith": "c_wraith",
    "Sigil": "c_sigil",
    "Ouija": "c_ouija",
    "Ectoplasm": "c_ectoplasm",
    "Immolate": "c_immolate",
    "Ankh": "c_ankh",
    "Deja Vu": "c_deja_vu",
    "Hex": "c_hex",
    "Trance": "c_trance",
    "Medium": "c_medium",
    "Cryptid": "c_cryptid",
    "The Soul": "c_soul",
    "Black Hole": "c_black_hole",
}

# 32 vouchers in game order (level-1 / level-2 alternate)
VOUCHERS = {
    "Overstock": "v_overstock_norm",
    "Overstock Plus": "v_overstock_plus",
    "Clearance Sale": "v_clearance_sale",
    "Liquidation": "v_liquidation",
    "Hone": "v_hone",
    "Glow Up": "v_glow_up",
    "Reroll Surplus": "v_reroll_surplus",
    "Reroll Glut": "v_reroll_glut",
    "Crystal Ball": "v_crystal_ball",
    "Omen Globe": "v_omen_globe",
    "Telescope": "v_telescope",
    "Observatory": "v_observatory",
    "Grabber": "v_grabber",
    "Nacho Tong": "v_nacho_tong",
    "Wasteful": "v_wasteful",
    "Recyclomancy": "v_recyclomancy",
    "Tarot Merchant": "v_tarot_merchant",
    "Tarot Tycoon": "v_tarot_tycoon",
    "Planet Merchant": "v_planet_merchant",
    "Planet Tycoon": "v_planet_tycoon",
    "Seed Money": "v_seed_money",
    "Money Tree": "v_money_tree",
    "Blank": "v_blank",
    "Antimatter": "v_antimatter",
    "Magic Trick": "v_magic_trick",
    "Illusion": "v_illusion",
    "Hieroglyph": "v_hieroglyph",
    "Petroglyph": "v_petroglyph",
    "Director's Cut": "v_directors_cut",
    "Retcon": "v_retcon",
    "Paint Brush": "v_paint_brush",
    "Palette": "v_palette",
}

# 30 blinds (bl_small/bl_big are not bosses)
BLINDS = {
    "Small Blind": "bl_small",
    "Big Blind": "bl_big",
    "The Ox": "bl_ox",
    "The Hook": "bl_hook",
    "The Mouth": "bl_mouth",
    "The Fish": "bl_fish",
    "The Club": "bl_club",
    "The Manacle": "bl_manacle",
    "The Tooth": "bl_tooth",
    "The Wall": "bl_wall",
    "The House": "bl_house",
    "The Mark": "bl_mark",
    "Cerulean Bell": "bl_final_bell",
    "The Wheel": "bl_wheel",
    "The Arm": "bl_arm",
    "The Psychic": "bl_psychic",
    "The Goad": "bl_goad",
    "The Water": "bl_water",
    "The Eye": "bl_eye",
    "The Plant": "bl_plant",
    "The Needle": "bl_needle",
    "The Head": "bl_head",
    "Verdant Leaf": "bl_final_leaf",
    "Violet Vessel": "bl_final_vessel",
    "The Window": "bl_window",
    "The Serpent": "bl_serpent",
    "The Pillar": "bl_pillar",
    "The Flint": "bl_flint",
    "Amber Acorn": "bl_final_acorn",
    "Crimson Heart": "bl_final_heart",
}

# 24 tags in game order
TAGS = {
    "Uncommon Tag": "tag_uncommon",
    "Rare Tag": "tag_rare",
    "Negative Tag": "tag_negative",
    "Foil Tag": "tag_foil",
    "Holographic Tag": "tag_holo",
    "Polychrome Tag": "tag_polychrome",
    "Investment Tag": "tag_investment",
    "Voucher Tag": "tag_voucher",
    "Boss Tag": "tag_boss",
    "Standard Tag": "tag_standard",
    "Charm Tag": "tag_charm",
    "Meteor Tag": "tag_meteor",
    "Buffoon Tag": "tag_buffoon",
    "Handy Tag": "tag_handy",
    "Garbage Tag": "tag_garbage",
    "Ethereal Tag": "tag_ethereal",
    "Coupon Tag": "tag_coupon",
    "Double Tag": "tag_double",
    "Juggle Tag": "tag_juggle",
    "D6 Tag": "tag_d_six",
    "Top-up Tag": "tag_top_up",
    "Skip Tag": "tag_skip",
    "Orbital Tag": "tag_orbital",
    "Economy Tag": "tag_economy",
}

# Tags unavailable before ante 2 (min_ante = 2)
TAG_MIN_ANTE = {
    "tag_negative": 2,
    "tag_standard": 2,
    "tag_meteor": 2,
    "tag_buffoon": 2,
    "tag_handy": 2,
    "tag_garbage": 2,
    "tag_ethereal": 2,
    "tag_top_up": 2,
    "tag_orbital": 2
}

# decks / backs
DECKS = {
    "Red Deck": "b_red",
    "Blue Deck": "b_blue",
    "Yellow Deck": "b_yellow",
    "Green Deck": "b_green",
    "Black Deck": "b_black",
    "Magic Deck": "b_magic",
    "Nebula Deck": "b_nebula",
    "Ghost Deck": "b_ghost",
    "Abandoned Deck": "b_abandoned",
    "Checkered Deck": "b_checkered",
    "Zodiac Deck": "b_zodiac",
    "Painted Deck": "b_painted",
    "Anaglyph Deck": "b_anaglyph",
    "Plasma Deck": "b_plasma",
    "Erratic Deck": "b_erratic",
    "Challenge Deck": "b_challenge",
}

# Booster packs.  The game has 2-4 art variants per pack (p_arcana_normal_1.._4, ...) with the
# variant weights summing to the analyzer's single weight; analyzers cannot tell variants apart,
# so oracle keys drop the numeric suffix.  Weight shown = summed weight of the variants.
PACKS = {
    "Arcana Pack": "p_arcana_normal",
    "Jumbo Arcana Pack": "p_arcana_jumbo",
    "Mega Arcana Pack": "p_arcana_mega",
    "Celestial Pack": "p_celestial_normal",
    "Jumbo Celestial Pack": "p_celestial_jumbo",
    "Mega Celestial Pack": "p_celestial_mega",
    "Standard Pack": "p_standard_normal",
    "Jumbo Standard Pack": "p_standard_jumbo",
    "Mega Standard Pack": "p_standard_mega",
    "Buffoon Pack": "p_buffoon_normal",
    "Jumbo Buffoon Pack": "p_buffoon_jumbo",
    "Mega Buffoon Pack": "p_buffoon_mega",
    "Spectral Pack": "p_spectral_normal",
    "Jumbo Spectral Pack": "p_spectral_jumbo",
    "Mega Spectral Pack": "p_spectral_mega",
}
PACK_WEIGHTS = {  # game order, summed over art variants; total 22.42
    "p_arcana_normal": 4, "p_arcana_jumbo": 2, "p_arcana_mega": 0.5,
    "p_celestial_normal": 4, "p_celestial_jumbo": 2, "p_celestial_mega": 0.5,
    "p_standard_normal": 4, "p_standard_jumbo": 2, "p_standard_mega": 0.5,
    "p_buffoon_normal": 1.2, "p_buffoon_jumbo": 0.6, "p_buffoon_mega": 0.15,
    "p_spectral_normal": 0.6, "p_spectral_jumbo": 0.3, "p_spectral_mega": 0.07,
}
# (kind, size, choices) -> pack key; analyzers expose kind + size + choices only
PACK_BY_SHAPE = {
    ("Arcana", 3, 1): "p_arcana_normal", ("Arcana", 5, 1): "p_arcana_jumbo", ("Arcana", 5, 2): "p_arcana_mega",
    ("Celestial", 3, 1): "p_celestial_normal", ("Celestial", 5, 1): "p_celestial_jumbo", ("Celestial", 5, 2): "p_celestial_mega",
    ("Standard", 3, 1): "p_standard_normal", ("Standard", 5, 1): "p_standard_jumbo", ("Standard", 5, 2): "p_standard_mega",
    ("Buffoon", 2, 1): "p_buffoon_normal", ("Buffoon", 4, 1): "p_buffoon_jumbo", ("Buffoon", 4, 2): "p_buffoon_mega",
    ("Spectral", 2, 1): "p_spectral_normal", ("Spectral", 4, 1): "p_spectral_jumbo", ("Spectral", 4, 2): "p_spectral_mega",
}

EDITIONS = {"No Edition": None, "": None, "Foil": "e_foil", "Holographic": "e_holo", "Polychrome": "e_polychrome", "Negative": "e_negative"}
ENHANCEMENTS = {"No Enhancement": None, "": None, "Bonus": "m_bonus", "Mult": "m_mult", "Wild": "m_wild", "Glass": "m_glass",
                "Steel": "m_steel", "Stone": "m_stone", "Gold": "m_gold", "Lucky": "m_lucky"}
# The game stores a card's seal as the bare colour string ('Red', 'Blue', 'Gold', 'Purple').
SEALS = {"No Seal": None, "": None, "Red Seal": "Red", "Blue Seal": "Blue", "Gold Seal": "Gold", "Purple Seal": "Purple"}
STAKES = {"White Stake": "stake_white", "Red Stake": "stake_red", "Green Stake": "stake_green", "Black Stake": "stake_black",
          "Blue Stake": "stake_blue", "Purple Stake": "stake_purple", "Orange Stake": "stake_orange", "Gold Stake": "stake_gold"}

# Playing cards: G.P_CARDS keys are "<S>_<R>" with S in H/C/D/S and R in 2..9,T,J,Q,K,A.
SUIT_NAMES = {"H": "Hearts", "C": "Clubs", "D": "Diamonds", "S": "Spades"}
RANK_NAMES = {"2": "2", "3": "3", "4": "4", "5": "5", "6": "6", "7": "7", "8": "8", "9": "9", "T": "10", "J": "Jack", "Q": "Queen", "K": "King", "A": "Ace"}

# Analyzer display names that differ from the game's own name field.
ANALYZER_ALIASES = {
    "Speed Tag": "Skip Tag",          # renamed in-game; Immolate lineage still prints Speed Tag
    "Drivers License": "Driver's License",
    "Mail In Rebate": "Mail-In Rebate",
    "Canio": "Caino",                 # the game's key/name is j_caino / "Caino"; analyzers spell it Canio
}

ALL_NAMED = {}
for _t in (JOKERS, TAROTS, PLANETS, SPECTRALS, VOUCHERS, BLINDS, TAGS, PACKS, DECKS):
    ALL_NAMED.update(_t)


def key_for(name: str, table: dict | None = None) -> str:
    """Map an analyzer display name to the game key; raises KeyError with a useful message."""
    t = table if table is not None else ALL_NAMED
    if name in t:
        return t[name]
    alias = ANALYZER_ALIASES.get(name)
    if alias is not None and alias in t:
        return t[alias]
    raise KeyError(f"no game key for analyzer name {name!r}")


def key_to_name(key: str) -> str | None:
    for n, k in ALL_NAMED.items():
        if k == key:
            return n
    return None
